# Generated by Django 2.1.5 on 2020-08-13 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='courses',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='course.Courses'),
            preserve_default=False,
        ),
    ]
