# Generated by Django 2.1.5 on 2020-08-12 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='curses_student',
            new_name='user_student',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='curse_teacher',
        ),
        migrations.AddField(
            model_name='curses',
            name='capacity_curse',
            field=models.IntegerField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curses',
            name='credits',
            field=models.IntegerField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='curses',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='school.Curses'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='dni',
            field=models.FloatField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='age',
            field=models.IntegerField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='curses',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='school.Curses'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='gender',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teacher',
            name='dni',
            field=models.FloatField(),
        ),
    ]
