# Generated by Django 2.1.5 on 2020-08-12 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_auto_20200811_2334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='name_student',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='name',
            new_name='name_teacher',
        ),
    ]
