# Generated by Django 2.1.5 on 2020-08-13 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_student_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('another', 'Weird')], default='Male', max_length=20),
        ),
    ]
