# Generated by Django 2.1.5 on 2020-08-12 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_auto_20200811_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='dni',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='dni',
            field=models.SlugField(),
        ),
    ]
